/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
          "surface-tint": "#4cd6ff",
          "surface-container-highest": "#2d3449",
          "background": "#0b1326",
          "secondary-fixed": "#ffdea8",
          "on-tertiary-container": "#005a3c",
          "tertiary": "#68f5b8",
          "primary": "#a4e6ff",
          "error-container": "#93000a",
          "surface-container-low": "#131b2e",
          "surface": "#0b1326",
          "on-error-container": "#ffdad6",
          "on-secondary": "#412d00",
          "on-error": "#690005",
          "tertiary-fixed-dim": "#4edea3",
          "on-secondary-container": "#6b4b00",
          "on-background": "#dae2fd",
          "surface-bright": "#31394d",
          "primary-container": "#00d1ff",
          "on-tertiary-fixed": "#002113",
          "error": "#ffb4ab",
          "tertiary-container": "#46d89d",
          "outline-variant": "#3c494e",
          "on-primary-container": "#00566a",
          "on-secondary-fixed": "#271900",
          "surface-variant": "#2d3449",
          "primary-fixed-dim": "#4cd6ff",
          "tertiary-fixed": "#6ffbbe",
          "secondary-container": "#feb700",
          "inverse-on-surface": "#283044",
          "on-surface": "#dae2fd",
          "primary-fixed": "#b7eaff",
          "surface-dim": "#0b1326",
          "surface-container": "#171f33",
          "on-tertiary-fixed-variant": "#005236",
          "secondary": "#ffdb9d",
          "on-primary-fixed": "#001f28",
          "secondary-fixed-dim": "#ffba20",
          "outline": "#859399",
          "inverse-primary": "#00677f",
          "on-primary": "#003543",
          "on-tertiary": "#003824",
          "surface-container-lowest": "#060e20",
          "on-secondary-fixed-variant": "#5e4200",
          "on-primary-fixed-variant": "#004e60",
          "on-surface-variant": "#bbc9cf",
          "surface-container-high": "#222a3d",
          "inverse-surface": "#dae2fd"
      },
      "spacing": {
          "gutter": "16px",
          "unit": "4px",
          "panel-padding": "12px",
          "margin-mobile": "16px",
          "margin-desktop": "24px"
      },
      "fontFamily": {
          "display-lg": ["Inter"],
          "body-sm": ["Inter"],
          "body-base": ["Inter"],
          "label-mono": ["JetBrains Mono"],
          "headline-md": ["Inter"],
          "label-caps": ["Inter"]
      },
      "fontSize": {
          "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
          "body-sm": ["14px", {"lineHeight": "20px", "letterSpacing": "0em", "fontWeight": "400"}],
          "body-base": ["16px", {"lineHeight": "24px", "letterSpacing": "0em", "fontWeight": "400"}],
          "label-mono": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500"}],
          "headline-md": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
          "label-caps": ["11px", {"lineHeight": "12px", "letterSpacing": "0.08em", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
}
